name: Ruby Security

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"
  push:
    branches: [ main ]

jobs:
  bundler_audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Scan for known security vulnerabilities in gems used
        run: bin/bundler-audit
